# Autogenerated wrapper script for CryptoMiniSat_jll for i686-linux-gnu-cxx03-mpi+mpich
export cryptominisat5, libcryptominisat5, libipasircryptominisat5

using GMP_jll
using Zlib_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("CryptoMiniSat")
JLLWrappers.@declare_library_product(libcryptominisat5, "libcryptominisat5.so.5.13")
JLLWrappers.@declare_library_product(libipasircryptominisat5, "libipasircryptominisat5.so.5.13")
JLLWrappers.@declare_executable_product(cryptominisat5)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, Zlib_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libcryptominisat5,
        "lib/libcryptominisat5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libipasircryptominisat5,
        "lib/libipasircryptominisat5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cryptominisat5,
        "bin/cryptominisat5",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
