# Autogenerated wrapper script for CryptoMiniSat_jll for x86_64-w64-mingw32-cxx11-mpi+microsoftmpi
export cryptominisat5, libcryptominisat5, libipasircryptominisat5

using GMP_jll
using Zlib_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("CryptoMiniSat")
JLLWrappers.@declare_library_product(libcryptominisat5, "libcryptominisat5win.dll")
JLLWrappers.@declare_library_product(libipasircryptominisat5, "libipasircryptominisat5.dll")
JLLWrappers.@declare_executable_product(cryptominisat5)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll, Zlib_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libcryptominisat5,
        "bin\\libcryptominisat5win.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libipasircryptominisat5,
        "bin\\libipasircryptominisat5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cryptominisat5,
        "bin\\cryptominisat5.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
